version: '3'

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ".env"
    ports:
      - "5432:5432"
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
    env_file:
      - ".env"

volumes:
  data:
