"""Rename lat column in city

Revision ID: d61474be05a1
Revises: ebd5b611281a
Create Date: 2024-04-05 23:44:15.078726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d61474be05a1"
down_revision: Union[str, None] = "ebd5b611281a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("city", sa.Column("lat", sa.Float(), nullable=False))
    op.drop_constraint("city_name_lan_lon_key", "city", type_="unique")
    op.create_unique_constraint(None, "city", ["name", "lat", "lon"])
    op.drop_column("city", "lan")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "city",
        sa.Column(
            "lan",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "city", type_="unique")
    op.create_unique_constraint("city_name_lan_lon_key", "city", ["name", "lan", "lon"])
    op.drop_column("city", "lat")
    # ### end Alembic commands ###
