"""Add pollution foreign key and city constraint

Revision ID: ebd5b611281a
Revises: 27fb1e1a297b
Create Date: 2024-04-05 22:49:32.733358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd5b611281a'
down_revision: Union[str, None] = '27fb1e1a297b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    op.create_unique_constraint(None, 'city', ['name', 'lan', 'lon'])
    op.add_column('pollution', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pollution_site_id'), 'pollution', ['site_id'], unique=False)
    op.create_foreign_key(None, 'pollution', 'city', ['site_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pollution', type_='foreignkey')
    op.drop_index(op.f('ix_pollution_site_id'), table_name='pollution')
    op.drop_column('pollution', 'site_id')
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    # ### end Alembic commands ###
