name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: |
          poetry add --dev pytest
          poetry run pytest

      - name: Static checking
        run: |
          poetry run mypy city_pollution --config-file pyproject.toml

      - name: Run Black check
        run: poetry run black --check --verbose city_pollution
